// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKHM1hPyLHL-IlU9GsGkLrNsGxpEPLmBw',
    appId: '1:782047419486:android:fb04349d530f142eb528cf',
    messagingSenderId: '782047419486',
    projectId: 'test-demo-a0620',
    storageBucket: 'test-demo-a0620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30eNusxSo0LBtz7lwWynB4283LRXa-Ro',
    appId: '1:782047419486:ios:cb38e8c50a5a5d12b528cf',
    messagingSenderId: '782047419486',
    projectId: 'test-demo-a0620',
    storageBucket: 'test-demo-a0620.firebasestorage.app',
    iosBundleId: 'com.example.testDemoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvDk2SadNHBILMmi0N-JIdmf33qTKWAsQ',
    appId: '1:782047419486:web:12ebe7256c303e76b528cf',
    messagingSenderId: '782047419486',
    projectId: 'test-demo-a0620',
    authDomain: 'test-demo-a0620.firebaseapp.com',
    storageBucket: 'test-demo-a0620.firebasestorage.app',
    measurementId: 'G-BR5CJ6N576',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDk2SadNHBILMmi0N-JIdmf33qTKWAsQ',
    appId: '1:782047419486:web:12ebe7256c303e76b528cf',
    messagingSenderId: '782047419486',
    projectId: 'test-demo-a0620',
    authDomain: 'test-demo-a0620.firebaseapp.com',
    storageBucket: 'test-demo-a0620.firebasestorage.app',
    measurementId: 'G-BR5CJ6N576',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30eNusxSo0LBtz7lwWynB4283LRXa-Ro',
    appId: '1:782047419486:ios:cb38e8c50a5a5d12b528cf',
    messagingSenderId: '782047419486',
    projectId: 'test-demo-a0620',
    storageBucket: 'test-demo-a0620.firebasestorage.app',
    iosBundleId: 'com.example.testDemoFirebase',
  );

}